name: Laravel Tests

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3, 8.4]
        laravel: [8.*, 9.*, 10.*, 11.*]
        dependency_version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 8.*
            dependency_version: prefer-lowest
          - laravel: 9.*
            dependency_version: prefer-lowest
            php: 8.2
          - laravel: 8.*
            php: [8.2, 8.3, 8.4]
          - laravel: 9.*
            php: [8.3, 8.4]
          - laravel: 10.*
            php: [8.0, 8.4]
          - laravel: 11.*
            php: [8.0, 8.1]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*

    name: php${{ matrix.php }} - laravel${{ matrix.laravel }} - ${{ matrix.dependency_version }}
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmatch, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency_version }} --prefer-dist --no-interaction

      - name: Running Tests
        run: ./vendor/bin/phpunit ./tests