name: Lumen Tests

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        lumen: [8.*, 9.*, 10.*]
        dependency_version: [prefer-lowest, prefer-stable]
        exclude:
          - lumen: 8.*
            dependency_version: prefer-lowest
          - lumen: 9.*
            dependency_version: prefer-lowest
            php: 8.2
          - lumen: 8.*
            php: 8.2
          - lumen: 8.*
            php: 8.3
          - lumen: 9.*
            php: 8.3
          - lumen: 10.*
            php: 8.0
        include:
          - lumen: 8.*
            testbench: 6.*
          - lumen: 9.*
            testbench: 7.*
          - lumen: 10.*
            testbench: 8.*

    name: php${{ matrix.php }} - lumen${{ matrix.lumen }} - ${{ matrix.dependency_version }}
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-lumen-${{ matrix.lumen }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmatch, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer require "laravel/lumen-framework:${{ matrix.lumen }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency_version }} --prefer-dist --no-interaction

      - name: Running Tests
        run: ./vendor/bin/phpunit ./tests